#!/bin/sh
echo `pwd`
sed -i "s/ _nop/__nop/g" $1
sed -i "s/	__nop/	__nop/g" $1
sed -i "s/_enable_interrupts/_EINT/g" $1
sed -i "s/_disable_interrupts/_DINT/g" $1
sed -i "s/ _bis_SR_register/__bis_SR_register/g" $1
sed -i "s/	_bis_SR_register/__bis_SR_register/g" $1
